/**:
  ros__parameters:
    use_sim_time: true
    execution_backend: simulation
    arm_trajectory_action: /arm_controller/follow_joint_trajectory
    gripper_trajectory_action: /gripper_controller/follow_joint_trajectory
    gripper_joint_name: joint7
    gripper_command_scale: 1.0
    gripper_feedback_scale: 1.0
    final_joint_tolerance: 0.05
    gripper_tolerance: 0.004
    action_server_timeout: 5.0
